# Избранные параметры событий яндекс метрики из документации API
# https://yandex.ru/dev/metrika/ru/logs/fields/hits

# Исключены:
# ym:pv:counterUserIDHash так как у нас все пользователи анонимные
# ym:pv:networkType так как устарела и будет удалена
# ym:pv:watchID так как всё равно будет присутствовать во всех запросах из-за разделения

params = [
    ('ym:pv:pageViewID', 'UInt32', 'pageViewID'),
    ('ym:pv:counterID', 'UInt32', 'counterID'),
    ('ym:pv:clientID', 'UInt64', 'clientID'),
    ('ym:pv:date', 'Date', 'date'),
    ('ym:pv:dateTime', 'DateTime', 'dateTime'),
    ('ym:pv:title', 'String', 'title'),
    ('ym:pv:pageCharset', 'String', 'pageCharset'),
    ('ym:pv:goalsID', 'Array(UInt32)', 'goalsID'),
    ('ym:pv:URL', 'String', 'URL'),
    ('ym:pv:referer', 'String', 'referer'),
    ('ym:pv:UTMCampaign', 'String', 'UTMCampaign'),
    ('ym:pv:UTMContent', 'String', 'UTMContent'),
    ('ym:pv:UTMMedium', 'String', 'UTMMedium'),
    ('ym:pv:UTMSource', 'String', 'UTMSource'),
    ('ym:pv:UTMTerm', 'String', 'UTMTerm'),
    ('ym:pv:openstatAd', 'String', 'openstatAd'),
    ('ym:pv:openstatCampaign', 'String', 'openstatCampaign'),
    ('ym:pv:openstatService', 'String', 'openstatService'),
    ('ym:pv:openstatSource', 'String', 'openstatSource'),
    ('ym:pv:operatingSystem', 'String', 'operatingSystem'),
    ('ym:pv:from', 'String', 'from'),
    ('ym:pv:hasGCLID', 'UInt8', 'hasGCLID'),
    ('ym:pv:GCLID', 'String', 'GCLID'),
    ('ym:pv:lastTrafficSource', 'String', 'lastTrafficSource'),
    ('ym:pv:lastSearchEngineRoot', 'String', 'lastSearchEngineRoot'),
    ('ym:pv:lastSearchEngine', 'String', 'lastSearchEngine'),
    ('ym:pv:lastAdvEngine', 'String', 'lastAdvEngine'),
    ('ym:pv:lastSocialNetwork', 'String', 'lastSocialNetwork'),
    ('ym:pv:lastSocialNetworkProfile', 'String', 'lastSocialNetworkProfile'),
    ('ym:pv:recommendationSystem', 'String', 'recommendationSystem'),
    ('ym:pv:messenger', 'String', 'messenger'),
    ('ym:pv:browser', 'String', 'browser'),
    ('ym:pv:browserMajorVersion', 'UInt16', 'browserMajorVersion'),
    ('ym:pv:browserMinorVersion', 'UInt16', 'browserMinorVersion'),
    ('ym:pv:browserCountry', 'String', 'browserCountry'),
    ('ym:pv:browserEngine', 'String', 'browserEngine'),
    ('ym:pv:browserEngineVersion1', 'UInt16', 'browserEngineVersion1'),
    ('ym:pv:browserEngineVersion2', 'UInt16', 'browserEngineVersion2'),
    ('ym:pv:browserEngineVersion3', 'UInt16', 'browserEngineVersion3'),
    ('ym:pv:browserEngineVersion4', 'UInt16', 'browserEngineVersion4'),
    ('ym:pv:browserLanguage', 'String', 'browserLanguage'),
    ('ym:pv:clientTimeZone', 'Int16', 'clientTimeZone'),
    ('ym:pv:cookieEnabled', 'UInt8', 'cookieEnabled'),
    ('ym:pv:deviceCategory', 'String', 'deviceCategory'),
    ('ym:pv:javascriptEnabled', 'UInt8', 'javascriptEnabled'),
    ('ym:pv:mobilePhone', 'String', 'mobilePhone'),
    ('ym:pv:mobilePhoneModel', 'String', 'mobilePhoneModel'),
    ('ym:pv:operatingSystemRoot', 'String', 'operatingSystemRoot'),
    ('ym:pv:physicalScreenHeight', 'UInt16', 'physicalScreenHeight'),
    ('ym:pv:physicalScreenWidth', 'UInt16', 'physicalScreenWidth'),
    ('ym:pv:screenColors', 'UInt8', 'screenColors'),
    ('ym:pv:screenFormat', 'String', 'screenFormat'),
    ('ym:pv:screenHeight', 'UInt16', 'screenHeight'),
    ('ym:pv:screenOrientation', 'UInt8', 'screenOrientation'),
    ('ym:pv:screenOrientationName', 'String', 'screenOrientationName'),
    ('ym:pv:screenWidth', 'UInt16', 'screenWidth'),
    ('ym:pv:windowClientHeight', 'UInt16', 'windowClientHeight'),
    ('ym:pv:windowClientWidth', 'UInt16', 'windowClientWidth'),
    ('ym:pv:ipAddress', 'String', 'ipAddress'),
    ('ym:pv:regionCity', 'String', 'regionCity'),
    ('ym:pv:regionCountry', 'String', 'regionCountry'),
    ('ym:pv:regionCityID', 'UInt32', 'regionCityID'),
    ('ym:pv:regionCountryID', 'UInt32', 'regionCountryID'),
    ('ym:pv:isPageView', 'UInt8', 'isPageView'),
    ('ym:pv:isTurboPage', 'UInt8', 'isTurboPage'),
    ('ym:pv:isTurboApp', 'UInt8', 'isTurboApp'),
    ('ym:pv:iFrame', 'UInt8', 'iFrame'),
    ('ym:pv:link', 'UInt8', 'link'),
    ('ym:pv:download', 'UInt8', 'download'),
    ('ym:pv:notBounce', 'UInt8', 'notBounce'),
    ('ym:pv:artificial', 'UInt8', 'artificial'),
    ('ym:pv:ecommerce', 'String', 'ecommerce'),
    ('ym:pv:params', 'String', 'params'),
    ('ym:pv:parsedParamsKey1', 'Array(String)', 'parsedParamsKey1'),
    ('ym:pv:parsedParamsKey2', 'Array(String)', 'parsedParamsKey2'),
    ('ym:pv:parsedParamsKey3', 'Array(String)', 'parsedParamsKey3'),
    ('ym:pv:parsedParamsKey4', 'Array(String)', 'parsedParamsKey4'),
    ('ym:pv:parsedParamsKey5', 'Array(String)', 'parsedParamsKey5'),
    ('ym:pv:parsedParamsKey6', 'Array(String)', 'parsedParamsKey6'),
    ('ym:pv:parsedParamsKey7', 'Array(String)', 'parsedParamsKey7'),
    ('ym:pv:parsedParamsKey8', 'Array(String)', 'parsedParamsKey8'),
    ('ym:pv:parsedParamsKey9', 'Array(String)', 'parsedParamsKey9'),
    ('ym:pv:parsedParamsKey10', 'Array(String)', 'parsedParamsKey10'),
    ('ym:pv:httpError', 'String', 'httpError'),
    ('ym:pv:shareService', 'String', 'shareService'),
    ('ym:pv:shareURL', 'String', 'shareURL'),
    ('ym:pv:shareTitle', 'String', 'shareTitle'),
]
