name: clickhouse

services:
  house:
    image: clickhouse:25.3.2.39
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_DB=metrika
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./data/:/var/lib/clickhouse:rw
      - ./logs/:/var/log/clickhouse-server:rw
  mysql:
    image: mysql:8.4.5
    environment:
      - MYSQL_DATABASE=data
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=app

    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

